apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lamp-ingress
spec:
  rules:
    - host: legacy.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lamp-web
                port:
                  number: 80
